# Generated by Django 3.2.10 on 2022-01-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_intro',
            field=models.TextField(blank='True', default='my intro', max_length=150, null=True),
        ),
    ]
