# Generated by Django 3.2.10 on 2022-01-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_short_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(blank='True', default='my intro', max_length=150, null=True),
        ),
    ]
