# Generated by Django 3.2.10 on 2022-01-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_short_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_link',
            field=models.TextField(blank='True', default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.TextField(blank='True', default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.TextField(blank='True', default='', max_length=300, null=True),
        ),
    ]
