# Generated by Django 3.2.10 on 2022-01-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220123_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.CharField(blank='True', default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_link',
            field=models.CharField(blank='True', default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_link',
            field=models.CharField(blank='True', default=' ', max_length=300, null=True),
        ),
    ]
