# Generated by Django 3.2.10 on 2022-01-23 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20220123_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profiles',
        ),
    ]
