# Generated by Django 3.2.10 on 2022-01-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_questions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
