# Generated by Django 3.2.10 on 2022-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_questions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
